Las columnas están todas capitalized y las columnas que son siglas están en mayúsculas. 
Me gusta como están así que no voy a realizar ninguna modificación.

A continuación procedo a poner un listado con las características de cada una de las columnas para cada csv:

DF ACTIVITY:

Loyalty Number
- 0 isna
- duplicated sum 388887
- Unique [100018, 100102, 100140, ..., 999731, 999788, 999891]
- Negatives: no
(df_activity["Loyalty Number"] < 0).sum() 
0
              
Year
- 0 isna
- Unique: only two values: 2017 and 2018
- Duplicates not relevant, year can be duplicated.
        
Month
- 0 isna
- Unique: [ 1, 9, 2, 3, 11, 4, 5, 7, 6, 8, 10, 12] <- this is ok.
- Duplicates not relevant, month can be duplicated.
        
Flights Booked
- 0 isna
- Unique: [ 3, 10,  6,  0,  8, 11,  9,  4,  7,  5,  2,  1, 12, 13, 14, 16, 15,
       17, 18, 19, 20, 21]
- Duplicates: 405602. Not relevant. A lot of people might have flown the same number of times.
        
Flights with Companions
- 0 isna
- Unique: [ 0, 4, 7, 1, 6, 3, 5, 2, 10, 8, 9, 11] <- this seems ok.
- Duplicates: 405612. Not relevant. A lot of people might have travelled the same amount of times with companions.
        
Total Flights
- 0 isna
- Unique: [ 3, 14,  6,  0, 15, 11, 12, 10,  8,  9,  7,  5, 16,  2,  1, 17, 13,
       22,  4, 19, 18, 21, 26, 20, 23, 25, 27, 24, 28, 30, 29, 31, 32]
- Unique contains 0 . So there are people that has not flown.
- Duplicated: 405591. Not relevant. A lot of people could have the same total of flights.

Distance
- 0 isna
- Unique: it can be 0. People that has not flown. 
- Duplicated: 400878. Not relevant. A lot of people may have the same kms. 
        
Points Accumulated
- 0 isna
- A lot of uniques. 
- A lot of duplicates

Points Redeemed
- 0 isna
- Unique: alot of uniques. Ranged from 0 to 875.
- Duplicated: a lot of duplicates

Dollar Cost Points Redeemed
- 0 isna
- Unique: [ 0, 28, 30, 25, 36, 32, 24, 26, 37, 33, 35, 27, 31, 54, 42, 29, 38,
       34, 39, 55, 41, 49, 40, 48, 45, 53, 58, 44, 43, 46, 52, 47, 63, 57,
       62, 51, 50, 64, 56, 61, 65, 60, 68, 59, 66, 69, 67, 71, 70]
- Duplicated: a lot of duplicates.
    
  
Data columns (total 10 columns):

n   Column                       Non-Null Count   Dtype  
 
 0   Loyalty Number               405624 non-null  int64  
 1   Year                         405624 non-null  int64  
 2   Month                        405624 non-null  int64  
 3   Flights Booked               405624 non-null  int64  
 4   Flights with Companions      405624 non-null  int64  
 5   Total Flights                405624 non-null  int64  
 6   Distance                     405624 non-null  int64  
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64  
 9   Dollar Cost Points Redeemed  405624 non-null  int64  
dtypes: float64(1), int64(9)

DF LOYALTY:

Loyalty Number
- 0 isna
- duplicated sum 0 
- Unique: [480934, 549612, 429460, ..., 776187, 906428, 652627]
- Negatives: no 
df_loyalty["Loyalty Number"].isna().sum()
0
        
        
Country
- 0 isna
- Duplicated: a lot. Most people will be from the same country. This makes sense.
- Unique: they are ALL from Canada. Only value. This column should not be taken into consideration for analysis since we are only working with customers from Canada. 

Province  
- 0 isna
- A lot of duplicates. People can be from the same Province. 
- Unique: ['Ontario', 'Alberta', 'British Columbia', 'Quebec', 'Yukon',
       'New Brunswick', 'Manitoba', 'Nova Scotia', 'Saskatchewan',
       'Newfoundland', 'Prince Edward Island']    <- validado que los territorios están en Canadá

City
- 0 isna
- Duplicates: a lot. Expected
- Unique: ['Toronto', 'Edmonton', 'Vancouver', 'Hull', 'Whitehorse',
       'Trenton', 'Montreal', 'Dawson Creek', 'Quebec City',
       'Fredericton', 'Ottawa', 'Tremblant', 'Calgary', 'Thunder Bay',
       'Whistler', 'Peace River', 'Winnipeg', 'Sudbury', 'West Vancouver',
       'Halifax', 'London', 'Regina', 'Kelowna', "St. John's", 'Victoria',
       'Kingston', 'Banff', 'Moncton', 'Charlottetown']  <- parece que todo bien. Ciudades correspondientes a territorios también están incluídas.

Postal Code
- 0 isna
- Duplicates: a lot. Expected
- Unique: ['M2Z 4K1', 'T3G 6Y6', 'V6E 3D9', 'P1W 1K4', 'J8Y 3Z5', 'Y2K 6R0',
       'P5S 6R4', 'K8V 4B2', 'H2Y 2W2', 'M8Y 4K8', 'U5I 4F1', 'G1B 3L5',
       'H4G 3T4', 'M2M 7K8', 'M2M 6J7', 'E3B 2H2', 'M1R 4K3', 'T9G 1W3',
       'H2Y 4R4', 'V5R 1W3', 'P1L 8X8', 'K1F 2R2', 'H5Y 2S9', 'V1E 4R6',
       'H2T 2J6', 'T3E 2V9', 'H2T 9K8', 'K8T 5M5', 'V6T 1Y8', 'P2T 6G3',
       'T9O 2W2', 'V6E 3Z3', 'R6Y 4T5', 'M5V 1G5', 'V6V 8Z3', 'B3J 9S2',
       'M5B 3E4', 'R2C 0M5', 'S6J 3G0', 'M2P 4F6', 'P1J 8T7', 'V09 2E9',
       'A1C 6H9', 'V10 6T5', 'B3C 2M8', 'M9K 2P4', 'T4V 1D4', 'R3R 3T4',
       'S1J 3C5', 'E1A 2A7', 'K1G 4Z0', 'H3T 8L4', 'C1A 6E8', 'H3J 5I6',
       'M3R 4K8']
         Técnicamente hay varios incorrectos: V10 6T5 , V09 2E9 no siguen el patrón de letra- numero - letra
        sacado por vistazo de formato todos parecen similares en la forma salvo esos dos. He revisado online por si había más info o algún código no funcional. durante el ejercicio se tratará el siguiente listado como inválido:

        'Y2K 6R0' – Invalid FSA (Y2K). The only valid FSAs in the Yukon start with Y1A.
        'U5I 4F1' – Invalid characters: U and I are not used in postal codes.
        'K1F 2R2' – While this format is valid, K1F is currently not an assigned FSA.
        'H5Y 2S9' – H5Y is not assigned.
        'H2T 9K8' – May not exist; H2T exists, but not all LDU ranges are used.
        'V09 2E9' – Invalid FSA (V09); FSAs starting with 0 are not used.
        'V10 6T5' – V10 is not a valid FSA (as of now).
                    
Gender
- O isna
- Duplicates: obviously there will be duplicates here.
- Unique: ['Female', 'Male'] <- this looks ok

Education
- 0 isna
- Duplicates: a lot. Expected.
- Unique: ['Bachelor', 'College', 'Master', 'High School or Below', 'Doctor']  <- this looks ok

Salary
- 4238 isna  - gente que no ha querido decir su salario?
- Duplicates: a lot. Expected
- Unique: [ 83236., nan, 103495., ..., 76178., 91970., -57297.]  <- NEGATIVE SALARIES. TO FIX
- 20 negatives
(df_loyalty['Salary'] < 0).sum() 
0

Marital Status
- 0 isna
- Duplicates: a lot. Expected
- Unique: ['Married', 'Divorced', 'Single']  <- looking good.

Loyalty Card
- 0 isna
- Duplicates: A lot of duplicates. Seeing how the options are it's normal that we can get dupes.
- Unique: ['Star', 'Aurora', 'Nova'] <- this seems ok.

CLV   (Valor total estimado que el cliente aporta a la empresa durante toda la relación que mantiene con ella.)
- 0 isna
- Duplicates: 8753. we can have people with same value.
- Unique: [ 3839.14, 3839.61, 3839.75, ..., 44771.3 , 50568.26, 61134.68]   <- max value 83325.38 min value 1898.01
        
Enrollment Type
- 0 isna
- Duplicates: 16735 . Since there are only two options it's normal to see duplicates.
- Unique: ['Standard', '2018 Promotion']  <- no me lo cargaría porque si se hace otra campaña en otro año en el futuro se puede comparar quienes entraron por la promo. Si quitamos esto y solo dejamos year sabemos en qué año entramos pero no si fue resultado de una campaña publicitaria.

Enrollment Year
-  0 isna
- Duplicates: 16730. los años se pueden repetir. Irrelevante.
- Unique: [2016, 2014, 2013, 2012, 2015, 2018, 2017]  <- all good
    
Enrollment Month
- 0 isna
- Duplicates: 16725
- Unique: [ 2, 3, 7, 10, 5, 6, 12, 1, 11, 8, 4, 9]  <- all good. Se puede cambiar a nombre de mes si nos sentimos extra currantes, para mejor legibilidad


Cancellation Year
- 14670 isna  <- puede haber nulos si hay gente que no ha cancelado
- Duplicates: 16730. not relevant.
- Unique: [ nan, 2018., 2015., 2017., 2014., 2016., 2013.]  <-  CAMBIARLO, UN AÑO NO DEBERÍA DE SER FLOAT. PASARLO A INT
        
Cancellation Month
- 14670 isna
- Duplicates: 16724. not relevant.
- Unique: [nan, 1., 12., 4., 2., 7., 11., 5., 6., 10., 8., 9., 3.]  <- CAMBIARLO. ESTO NO DEBE DE SER FLOAT. PASARLO A INT O A DATE PERO NO FLOAT.


Data columns (total 16 columns):

 n   Column              Non-Null Count  Dtype  
  
 0   Loyalty Number      16737 non-null  int64  
 1   Country             16737 non-null  object 
 2   Province            16737 non-null  object 
 3   City                16737 non-null  object 
 4   Postal Code         16737 non-null  object 
 5   Gender              16737 non-null  object 
 6   Education           16737 non-null  object 
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object 
 9   Loyalty Card        16737 non-null  object 
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object 
 12  Enrollment Year     16737 non-null  int64  
 13  Enrollment Month    16737 non-null  int64  
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)


COSAS EN COMÚN:
-Es normal que hay diferencia duplicados en loyalty number. En loyalty es como base de datos de clientes así que no puede haber duplicados. Y en activity puede aparecer un cliente 27 veces si voló mucho.
No se borran duplicados por esta razón. Se entiende que está correcta.

ACTIVITY:
-se podrían combinar year y month en una columna que fuese date? No combinamos ambas. Es más fácil para filtrar por separado, el mes lo dificultaría. 
-Distance no se le añade kms al final porque sino lo pasa a string y no podemos hacer cosas con eso.
-hay gente que nunca voló.
-points accumulated es float,y yo creo que debería de ser INT. No creo que haya decimales en los puntos acumulados
-Dollar Cost Points Redeemed: No ponemos simbolo de dólar por si queremos hacer algo con esos números, añadirlo lo convertiría a string y dificultaría las cosas, así que es mejor mantenerlo como está que desde mi punto de vista está bien ya que la propia columna te indica que está en dólares. Está en int. Pensé en pasarlo a float por si acaso en el futuro hay decimales.

LOYALTY:
-cancellation year y cancellation month están como float. Sería int. No tiene sentido que esté como float. 
-todos los clientes son de Canadá. No hacemos drop de esta columna. La dejamos porque puede ser que haya clientes en un futuro que no sean de Canadá a no ser que la aerolínea esté restricted a nacionales. Dado que no es algo que el cliente haya confirado la dejamos. Igual en el futuro expanden sedes y nos interesa saber de dónde son.
-negative salaries. To fix. It also has nulls but maybe that's expected since not everyone will be willing to share their earnings.
-postal code. Cambiar a nulos los códigos inválidos para evitar errores en el futuro.
-CLV es float. No cambiaría eso creo porque los decimales tal vez afecten a un posible ranking.
-Enrollment year es int , dejarlo asi porque como int es más fácil de gestionar
-Enrollment month es int , dejarlo asi porque es más fácil de gestionar si está en numero y no en texto
-Cancellation year - pasarlo a int. PERO CLARO HAY NAN. IGUAL METER TRY EXCEPT. FUNCIONA YAYYYYY
-Cancellation month - pasarlo a int. HAY NAN. Same scenario. Igual puedo usar la misma función tbh. Cambiada a un nombre más genérico porque ante estaba más tailored para year.


--------------------------


DESCRIPCIÓN DE CADA COLUMNA

ANALYSIS

 Loyalty Number: Este atributo representa un identificador único para cada cliente dentro del
 programa de lealtad de la aerolínea. Cada número de lealtad corresponde a un cliente específico.

 Year: Indica el año en el cual se registraron las actividades de vuelo para el cliente.
 
 Month: Representa el mes del año (de 1 a 12) en el cual ocurrieron las actividades de vuelo.

 Flights Booked: Número total de vuelos reservados por el cliente en ese mes específico.

 Flights with Companions: Número de vuelos reservados en los cuales el cliente viajó con
 acompañantes.

 Total Flights: El número total de vuelos que el cliente ha realizado, que puede incluir vuelos
 reservados en meses anteriores.

 Distance: La distancia total (presumiblemente en millas o kilómetros) que el cliente ha volado
 durante el mes.

 Points Accumulated: Puntos acumulados por el cliente en el programa de lealtad durante el mes,
 con base en la distancia volada u otros factores.

 Points Redeemed: Puntos que el cliente ha redimido en el mes, posiblemente para obtener
 beneficios como vuelos gratis, mejoras, etc.

 Dollar Cost Points Redeemed: El valor en dólares de los puntos que el cliente ha redimido durante
 el mes.


LOYALTY

Loyalty Number: Identificador único del cliente dentro del programa de lealtad. Este número permite
 correlacionar la información de este archivo con el archivo de actividad de vuelos. 

Country: País de residencia del cliente.

Province: Provincia o estado de residencia del cliente (aplicable a países con divisiones provinciales
 o estatales, como Canadá).

City: Ciudad de residencia del cliente.

Postal Code: Código postal del cliente.

Gender: Género del cliente (ej. Male para masculino y Female para femenino).

Education: Nivel educativo alcanzado por el cliente (ej. Bachelor para licenciatura, College para
estudios universitarios o técnicos, etc.).

Salary: Ingreso anual estimado del cliente.
Marital Status: Estado civil del cliente (ej. Single para soltero, Married para casado, Divorced para
divorciado, etc.).

Loyalty Card: Tipo de tarjeta de lealtad que posee el cliente. Esto podría indicar distintos niveles o
categorías dentro del programa de lealtad.

CLV (Customer Lifetime Value): Valor total estimado que el cliente aporta a la empresa durante
toda la relación que mantiene con ella.

Enrollment Type: Tipo de inscripción del cliente en el programa de lealtad (ej. Standard).

Enrollment Year: Año en que el cliente se inscribió en el programa de lealtad.

Enrollment Month: Mes en que el cliente se inscribió en el programa de lealtad.

Cancellation Year: Año en que el cliente canceló su membresía en el programa de lealtad, si aplica.

Cancellation Month: Mes en que el cliente canceló su membresía en el programa de lealtad, si
aplica.

Análisis más en detalle de nulos, en porcentaje:

ACTIVITY no tiene nulls
- Loyalty Number                 0.0
- Year                           0.0
- Month                          0.0
- Flights Booked                 0.0
- Flights with Companions        0.0
- Total Flights                  0.0
- Distance                       0.0
- Points Accumulated             0.0
- Points Redeemed                0.0
- Dollar Cost Points Redeemed    0.0
dtype: float64


LOYALTY
- Loyalty Number         0.00
- Country                0.00
- Province               0.00
- City                   0.00
- Postal Code            0.00
- Gender                 0.00
- Education              0.00
- Salary                25.32
- Marital Status         0.00
- Loyalty Card           0.00
- CLV                    0.00
- Enrollment Type        0.00
- Enrollment Year        0.00
- Enrollment Month       0.00
- Cancellation Year     87.65
- Cancellation Month    87.65
dtype: float64
----------------------
NOTA: ACTIVITY NO TIENE OBJECTS AS A TYPE, ENTONCES NO SE PUEDEN INCLUÍR PARA EL DESCRIBE DE OBJECTS OBVIAMENTE.
-----------------------

CONCLUSIONES
-Revisando los nulos llegamos a la conclusión de que solamente un 12.35% de los clientes canceló la membresía. Dado que entendemos los no-nulos como gente que ha cancelado membresía.
No quitaría los clientes que hayan cancelado porque podrían regresar en cualquier momento, y además es información que tal vez nos interese tener para un análisis sobre retención de clientes (ej: en qué ciudad se han dado más de baja? Tal vez haya algo mal en una sede en específico que se tenga que revisar) 


-Un 25.32% de los clientes no tienen un salario añadido. Esto puede ser esperable dado que la gente podría ser reticente a compartir cierta información como en este caso el salario.

-El género femenino es el que más tiene membresía en el programa de lealtad.
-Hay más gente casada con membresía en el programa
-Star es la loyalty card que más se ve.
-Toronto destaca como ciudad en la que hay más membresías.

-Hay gente que metió mal su código postal. Voy a dejar la columna pero cambiar los valores incorrectos por NA/NAN para que no den lugar a confusión.

-Como curiosidad, hay gente que nunca ha volado si nos fijamos en total flights ya que hay gente con 0 en total.

-En enrollment type solo hay standard y una promo de 2018. no nos cargamos la columna por tenerla para posibles comparativas de campaña en futuro, o por si se decide hacer algo con esa gente de 2018 de esa campaña.

-Points accumulated lo pasaría a int. Aunque sea en base a distancia volada no debería de haber medios puntos, o tienes 3 puntos o tienes 4 por ejemplo pero no 3.5. Al hacer la conversión redondea para abajo.
Hay una cosa llamada math ceil para poder redondear para arriba, pero como no la vimos no voy a hacerlo. De todos modos lo redondearía igual y haría un aviso en la web/redes sociales de que los puntos acumulados se redondean y que puede haber una ligera variación debido a ello.  - PREGUNTARLE A CESAR?

-Todos los negativos en salario entraron en la promo de 2018, pero no todos los de esa promo tienen mal el salario! Cambiamos negativos a positivos ya que parece que son unas cifras que podrían haberse metido en negativo sin querer. Hay bastante diferencia en los salarios para el mismo nivel de educación pero igual depende de la empresa en la que esté/cargo. 






-Es normal que hay diferencia duplicados en loyalty, en loyalty es como base de datos de clientes así que no puede haber duplicados. Y en activity puede aparecer un cliente 27 veces si voló mucho.
No se borran duplicados por esta razón. Se entiende que está correcta.


-hay gente que ha cancelado y que todavía le quedan puntos acumulados. Se les podría enviar un email de campaña para intentar recuperar a esos clientes indicándoles que todavía conservan sus puntos.